# Generated by Django 5.2.9 on 2025-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Iran', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/'),
        ),
    ]
