# Generated by Django 5.2.9 on 2025-12-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productstore',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
